#!/usr/bin/env python3
"""Build a review package for a finished /teamlead run.

Emits a directory an external agent can be pointed at:

    <out>/PROMPT.md   the prompt: task, base SHA, commits, changed files, rubric
    <out>/plan.md     the run's plan, copied verbatim (the spec excerpt lives here)
    <out>/<input>.md  any run file the task itself points at (see referenced_inputs)
    <out>/diff.patch  only with --with-diff

The prompt names commits and files rather than inlining the diff, so it stays
small; the reviewing agent reads the diff from the repo itself.

Usage:
    review_package.py [target] [options]

    target      a run directory, a repo/worktree path, or nothing (uses cwd).
                A repo path picks the newest run whose repo.txt matches it.

Options:
    --base SHA        override the base commit (default: derived, see below)
    --head REF        head to review (default: HEAD)
    --out DIR         output directory (default: <run>/review-package)
    --plan FILE       plan file to copy when there is no run directory
    --task FILE       file whose contents are the request, when there is no
                      run task.md
    --with-diff       also write diff.patch and reference it from the prompt
    --quiet           print only the output directory
"""

from __future__ import annotations

import argparse
import re
import shutil
import subprocess
import sys
from pathlib import Path

import paths

RUNS_ROOT = paths.runs_dir()
SHA_RE = re.compile(r"\b([0-9a-f]{7,40})\b")
# Long commit lists are noise: the prompt asks for the change to be reviewed as
# one unit, so a list of every reachable commit argues against its own advice.
COMMIT_LIST_CAP = 20
# The run's own conclusions. Excluded on purpose — a self-report hands the
# reviewer the verdicts it was asked to reach independently. `questions.md` is
# here for its questions and its `recommended:` lines, which are the planner's
# opinion; its `## Answers` are the user's and ship separately as answers.md.
SELF_REPORT_RE = re.compile(
    r"^(?:plan|plan-validation|final-report|questions)\.md$"
    r"|^(?:implementer|verifier|triage)-"
    r"|^review-r\d"
)
ANSWERS_RE = re.compile(r"^## Answers$(.*?)(?=^## |\Z)", re.MULTILINE | re.DOTALL)
MD_REF_RE = re.compile(r"([\w.+-]+\.md)\b")
# --plan is often pointed at a document that was never generated by this skill
# (a PR body, a design note). Promising the reviewer sections it does not have
# earns a finding that no scope boundary was declared, so the wording adapts.
#
# Every marker the structured wording names is listed here, because this tuple
# and that paragraph are one claim written twice. Checking a subset was the
# defect: four global headings said nothing about whether the per-workstream
# acceptance criteria, test plans and reuse lines existed, and the prompt
# asserted them anyway. `references/roles/planner.md` is the source of the list,
# and it is also the source of the split below — the first four markers live
# inside each `## WS-<N>` block and the last three are written once for the
# whole plan, which is the difference between "this document contains the words"
# and "the reviewer will find this where the prompt says to look".
WORKSTREAM_RE = re.compile(r"^## WS-.*?(?=^## |\Z)", re.MULTILINE | re.DOTALL)
WORKSTREAM_SECTIONS = (
    "### Spec excerpt",
    "### Observable acceptance",
    "### Test plan",
    "### Reuse and scope",
)
GLOBAL_SECTIONS = (
    "## Decisions taken",
    "## Project forbiddens",
    "## Anti-scope",
)
PLAN_SECTIONS = WORKSTREAM_SECTIONS + GLOBAL_SECTIONS
REUSE_SECTION = "### Reuse and scope"
# `reuse:` and `keep because:` are unconditional in the planner's template; a
# `do not reuse:` line exists only "where it applies", so requiring it would
# report a correct plan as incomplete. The prompt's wording matches this split.
REUSE_LINES = ("reuse:", "keep because:")
# Real plans write these markers as `reuse:`, **reuse:**, `- \x60reuse:\x60` and
# plain `reuse:` in roughly equal measure. Measured against 75 generated plans, a
# bare line-start match called 30 of them incomplete over nothing but a backtick
# — the same false report as announcing material that is not there, aimed the
# other way, and the one the task named explicitly. Anchoring stays at the line
# start so `do not reuse:` can never satisfy the `reuse:` requirement.
MARKER_PREFIX = r"^[ \t]*(?:[-*+][ \t]+)?[`*_]{0,2}"


# An opener carries an info string (```markdown, ```python); a bare fence only
# ever closes. Markdown itself cannot nest same-length fences — any bare run of
# three backticks closes the block — so a plan that quotes a spec which itself
# contains a code fence inverts the parity of every fence after it. Three real
# plans in the corpus do exactly that, and pairing bare fences swallowed their
# genuine `### Observable acceptance` onwards. Requiring the info string means
# those plans are read intact, and an unterminated fence now matches nothing
# rather than consuming the rest of the document. Both choices fail toward
# stripping too little, because too little is the pre-existing permissiveness
# while too much invents a false rejection of a real plan.
FENCE_RE = re.compile(
    r"^[ \t]*(```|~~~)[ \t]*\S[^\n]*\n.*?^[ \t]*\1[ \t]*$", re.MULTILINE | re.DOTALL
)
# A heading is the marker itself, optionally annotated in parentheses — nothing
# else. The tail was previously unconstrained, so `### Spec excerpt appendix`
# satisfied `### Spec excerpt` and the prompt then named a section the document
# did not have. Measured over 173 real plans, the tail is empty 1510 times and
# parenthesised 5 (`(verbatim from task.md)`, `(WS-3)`); nothing else occurs. So
# this accepts every real heading while rejecting a different name that merely
# starts the same way, which is the distinction the announcement depends on.
HEADING_TAIL = r"[ \t]*(?:\([^\n]*\))?[ \t]*$"


def without_fenced_blocks(text: str) -> str:
    """The document with fenced code spans removed, newlines kept as separators.

    A plan that quotes the planner's own template inside a ```markdown fence is
    showing what a section looks like, not carrying one, and counting it meant a
    plan could satisfy every heading requirement while its real workstreams were
    empty.

    Only a labelled block is removed, which leaves one gap open on purpose: the
    same template quoted inside a bare fence still counts. That is the old
    behaviour rather than a new fault, and it is the price of never removing a
    section a plan really has — measured across 174 plans, this removes no
    heading from any of them.
    """
    return FENCE_RE.sub("\n", text)


def section_body(text: str, marker: str) -> str:
    """The content under `marker`, empty if the heading is absent or carries none.

    Absent and empty are deliberately one answer. The prompt uses this to decide
    whether to promise a reviewer that material exists, and a heading with
    nothing under it buys that reviewer exactly nothing — it is the shape a
    truncated or templated plan takes, and telling someone to go read a spec
    excerpt that is a blank line wastes the same trip as telling them to read one
    that was never written.

    The stop condition is the next heading at the same level or higher, worked
    out from the marker's own `#` count, so a `### Test plan` ends at the next
    `###`/`##`/`#` and not at a `#### ` beneath it.
    """
    level = len(marker) - len(marker.lstrip("#"))
    match = re.search(
        rf"^{re.escape(marker)}{HEADING_TAIL}\n(.*?)(?=^#{{1,{level}}} |\Z)",
        text,
        re.MULTILINE | re.DOTALL,
    )
    return match.group(1).strip() if match else ""


def missing_plan_sections(text: str) -> list[str]:
    """Which advertised sections this plan does not usably have, in order.

    Absence is reported per section rather than as one flag because the prompt
    has to describe a partial plan without lying in either direction. Saying a
    plan "has no `## Anti-scope`" when it has one is the same class of error as
    claiming spec excerpts it lacks: both teach the reviewer to distrust the
    package, and one of them cost a real review a false defect against the
    change.

    A workstream marker has to hold in EVERY `## WS-` block, because that is what
    "per workstream" means and a reviewer sent to WS-2 does not care that WS-1
    was complete. Searching the document once satisfied a plan whose second
    workstream was an empty heading, and satisfied a bare skeleton of all seven
    headings with no content anywhere — both of which the prompt then announced
    as carrying the full material. A plan with no workstream blocks at all fails
    every one of them: "per workstream" over zero workstreams is a claim about
    nothing.
    """
    missing: list[str] = []
    text = without_fenced_blocks(text)
    workstreams = WORKSTREAM_RE.findall(text)
    for marker in WORKSTREAM_SECTIONS:
        bodies = [section_body(block, marker) for block in workstreams]
        if not workstreams or not all(bodies):
            missing.append(marker)
        elif marker == REUSE_SECTION and not all(
            re.search(rf"{MARKER_PREFIX}{re.escape(line)}", body, re.MULTILINE)
            for body in bodies
            for line in REUSE_LINES
        ):
            missing.append(marker)
    missing += [marker for marker in GLOBAL_SECTIONS if not section_body(text, marker)]
    return missing


def plan_is_structured(text: str) -> bool:
    """Does the plan carry every section the prompt is about to claim it has?

    This was one alternation search, so a single heading made a plan "structured"
    and the prompt then asserted the whole set. Tightening it to four headings
    fixed the cheap half and left the expensive one: the paragraph promises
    material *per workstream*, with contents, which headings found anywhere in
    the document are no evidence of at all. The rule is that the check and the
    claim name the same sections, in the same places — so the claim is true
    whenever it is made.
    """
    return not missing_plan_sections(text)


class Fail(Exception):
    pass


def git(repo: Path, *args: str, check: bool = True) -> str:
    proc = subprocess.run(
        ["git", "-C", str(repo), *args],
        capture_output=True,
        text=True,
    )
    if check and proc.returncode != 0:
        raise Fail(f"git {' '.join(args)} failed: {proc.stderr.strip()}")
    return proc.stdout.strip()


def is_repo(path: Path) -> bool:
    proc = subprocess.run(
        ["git", "-C", str(path), "rev-parse", "--git-dir"],
        capture_output=True,
        text=True,
    )
    return proc.returncode == 0


def is_run_dir(path: Path) -> bool:
    return (path / "plan.md").is_file() and (path / "repo.txt").is_file()


def newest_run_for_repo(repo: Path) -> Path | None:
    want = repo.resolve()
    candidates = []
    for repo_txt in RUNS_ROOT.glob("*/*/repo.txt"):
        try:
            recorded = Path(repo_txt.read_text().strip()).resolve()
        except OSError:
            continue
        if recorded == want:
            candidates.append(repo_txt.parent)
    if not candidates:
        return None
    return sorted(candidates, key=lambda p: p.name)[-1]


def recent_runs(limit: int = 10) -> list[tuple[Path, Path, bool]]:
    """(run_dir, repo, repo_exists) for the newest runs, newest first."""
    rows = []
    for repo_txt in RUNS_ROOT.glob("*/*/repo.txt"):
        try:
            repo = Path(repo_txt.read_text().strip()).expanduser()
        except OSError:
            continue
        rows.append((repo_txt.parent, repo, repo.exists()))
    rows.sort(key=lambda row: row[0].name, reverse=True)
    return rows[:limit]


def format_recent(limit: int = 10) -> str:
    rows = recent_runs(limit)
    if not rows:
        return "No teamlead runs found under runs/."
    out = ["Recent runs — pass one of these paths, or the repo path beside it:"]
    for run_dir, repo, exists in rows:
        mark = "" if exists else "   (repo missing)"
        out.append(f"  {run_dir}")
        out.append(f"      repo: {repo}{mark}")
    return "\n".join(out)


def resolve_target(raw: str | None) -> tuple[Path | None, Path]:
    """Return (run_dir_or_None, repo)."""
    target = Path(raw).expanduser() if raw else Path.cwd()
    if not target.exists():
        raise Fail(f"target does not exist: {target}")
    target = target.resolve()

    if is_run_dir(target):
        repo = Path((target / "repo.txt").read_text().strip()).expanduser()
        if not repo.exists():
            raise Fail(f"repo.txt points at a missing path: {repo}")
        return target, repo.resolve()

    if is_repo(target):
        repo = Path(git(target, "rev-parse", "--show-toplevel")).resolve()
        return newest_run_for_repo(repo), repo

    hint = "no target given, so the current directory was used" if not raw else ""
    raise Fail(
        f"{target} is neither a teamlead run directory nor a git repo"
        + (f" ({hint})" if hint else "")
        + "\n\n"
        + format_recent()
    )


def recorded_commits(run_dir: Path | None, repo: Path) -> list[str]:
    """SHAs the implementer reports claim, verified to exist in the repo."""
    if run_dir is None:
        return []
    found: list[str] = []
    for report in sorted(run_dir.glob("implementer-*.md")):
        in_commits = False
        for line in report.read_text(errors="replace").splitlines():
            stripped = line.strip()
            if stripped.startswith("## "):
                in_commits = stripped.lower().startswith("## commits")
                continue
            if stripped.lower().startswith("commits:"):
                found += SHA_RE.findall(stripped.split(":", 1)[1])
            elif in_commits:
                m = re.match(r"^([0-9a-f]{7,40})\s", stripped)
                if m:
                    found.append(m.group(1))
    verified = []
    for sha in dict.fromkeys(found):
        proc = subprocess.run(
            ["git", "-C", str(repo), "rev-parse", "--verify", f"{sha}^{{commit}}"],
            capture_output=True,
            text=True,
        )
        if proc.returncode == 0:
            verified.append(proc.stdout.strip())
    return verified


def upstream_ref(repo: Path) -> str | None:
    for ref in ("origin/main", "origin/master", "origin/HEAD"):
        proc = subprocess.run(
            ["git", "-C", str(repo), "rev-parse", "--verify", ref],
            capture_output=True,
            text=True,
        )
        if proc.returncode == 0:
            return ref
    return None


def oldest_commit(repo: Path, shas: list[str], head: str) -> str | None:
    """The recorded SHA that is furthest from head along first-parent history."""
    order = git(repo, "rev-list", head).splitlines()
    positions = {sha: order.index(sha) for sha in shas if sha in order}
    if not positions:
        return None
    return max(positions, key=lambda sha: positions[sha])


def resolve_base(
    repo: Path, head: str, recorded: list[str], override: str | None
) -> tuple[str, list[str]]:
    """Return (base_sha, warnings)."""
    warnings: list[str] = []
    upstream = upstream_ref(repo)

    if override:
        base = git(repo, "rev-parse", "--verify", f"{override}^{{commit}}")
    else:
        base = None
        if upstream:
            base = git(repo, "merge-base", upstream, head, check=False) or None
        if base is None:
            oldest = oldest_commit(repo, recorded, head)
            if oldest is None:
                raise Fail(
                    "cannot derive a base: no upstream ref and no recorded "
                    "commits. Pass --base <sha>."
                )
            base = git(repo, "rev-parse", f"{oldest}^")
            warnings.append(
                "No origin/main-style ref found; base is the parent of the "
                "oldest commit recorded by the run."
            )

    local_main = git(repo, "rev-parse", "--verify", "main", check=False)
    if upstream and local_main:
        upstream_sha = git(repo, "rev-parse", upstream)
        if local_main != upstream_sha:
            warnings.append(
                f"Local `main` ({local_main[:8]}) differs from {upstream} "
                f"({upstream_sha[:8]}) — diffing against local main would lie. "
                "This package uses the SHA below, not a branch name."
            )

    in_range = set(git(repo, "rev-list", f"{base}..{head}").splitlines())
    missing = [s for s in recorded if s not in in_range]
    if missing:
        warnings.append(
            "Commits recorded by the run that are NOT in base..head: "
            + ", ".join(s[:8] for s in missing)
            + ". The base may be wrong — check with --base."
        )
    unrecorded = [s for s in in_range if s not in set(recorded)]
    if recorded and unrecorded:
        warnings.append(
            f"{len(unrecorded)} commit(s) in base..head are not recorded in any "
            "implementer report. They are still included in this review — the "
            "status block is often omitted from the report file."
        )
    return base, warnings


def commit_log(
    repo: Path, base: str, head: str, paths: list[str]
) -> list[tuple[str, str]]:
    args = ["log", "--reverse", "--format=%h\t%s", f"{base}..{head}"]
    if paths:
        args += ["--", *paths]
    rows = []
    for line in git(repo, *args).splitlines():
        sha, _, subject = line.partition("\t")
        rows.append((sha, subject))
    return rows


def commits_in_scope(
    repo: Path, base: str, head: str, changed: list[str]
) -> tuple[list[tuple[str, str]], dict[str, int]]:
    """The commits worth listing, plus the counts that explain the omissions.

    A range can reach commits that leave no trace in its own diff — reverted
    later, or merged in from history the base already carries. On a branch that
    merged a squash-landed sibling, 16 of 69 were of that kind, so the list was
    dominated by commits the reviewer cannot see the effect of.
    """
    every = commit_log(repo, base, head, [])
    touching = every
    # A path filter longer than this is its own kind of noise, and the argv
    # limit becomes a real risk; a change that wide has no list problem anyway.
    if changed and len(changed) <= 100:
        touching = commit_log(repo, base, head, changed)
    shown = touching[-COMMIT_LIST_CAP:]
    return shown, {
        "total": len(every),
        "touching": len(touching),
        "shown": len(shown),
    }


def referenced_inputs(run_dir: Path | None, task: str) -> list[Path]:
    """Run files the task text points at, excluding the run's own reports.

    When the task is "fix all the issues from this review", the review itself
    is the acceptance criteria — and it lives in a file beside the task
    (`$RUN/review-feedback.md`), named by a variable the reviewing agent cannot
    expand. Copying those inputs is what lets the reviewer check the primary
    criterion instead of inferring it.
    """
    if run_dir is None:
        return []
    found: dict[str, Path] = {}
    for name in MD_REF_RE.findall(task):
        if name in found or SELF_REPORT_RE.search(name):
            continue
        candidate = run_dir / name
        if candidate.is_file():
            found[name] = candidate
    return list(found.values())


def user_answers(run_dir: Path | None) -> str:
    """The `## Answers` block of questions.md — the user's decisions, verbatim.

    The rest of that file is the run's own thinking: the questions it chose to
    ask and the option it recommended. The answers are the opposite thing — the
    user amending the task after it was written — so withholding them grades
    the diff against a request that was superseded before the first commit. One
    review opened a HIGH plan defect for exactly that, against two answers that
    predated the work by eighteen minutes.

    A run that asks a second round appends a second `## Answers`, so every block
    ships, in file order. The first one alone is a decision the user has already
    superseded.
    """
    if run_dir is None:
        return ""
    questions = run_dir / "questions.md"
    if not questions.is_file():
        return ""
    blocks = ANSWERS_RE.findall(questions.read_text(errors="replace"))
    body = "\n\n".join(b.strip() for b in blocks if b.strip())
    return f"# Answers\n\n{body}\n" if body else ""


def numstat(repo: Path, base: str, head: str) -> list[tuple[str, str, str]]:
    rows = []
    out = git(repo, "diff", "--numstat", f"{base}..{head}")
    for line in out.splitlines():
        parts = line.split("\t")
        if len(parts) == 3:
            rows.append((parts[0], parts[1], parts[2]))
    return rows


def working_tree_changes(repo: Path) -> list[str]:
    out = git(repo, "status", "--porcelain")
    return [line for line in out.splitlines() if line.strip()]


def build_prompt(ctx: dict) -> str:
    repo = ctx["repo"]
    base, head_sha = ctx["base"], ctx["head_sha"]
    lines: list[str] = []
    add = lines.append

    add("# Code review request — one change, reviewed as a whole")
    add("")
    add(
        "You are reviewing a completed change written by an AI coding agent. "
        "Review it as ONE unit of work. Do NOT review commit by commit: the "
        "history is TDD-shaped (a commit whose tests are meant to fail, then "
        "the fix) and rework-shaped (later rounds strengthen earlier "
        "assertions), so individual commits are states nobody intends to keep."
    )
    add("")
    add("## Where the change is")
    add("")
    add(f"- Repo / worktree: `{repo}`")
    add(f"- Branch: `{ctx['branch']}`")
    add(f"- Base commit: `{base}`")
    add(f"- Head commit: `{head_sha}`")
    add("")
    add("Read the whole change with:")
    add("")
    add("```")
    add(f"git -C {repo} diff {base[:12]}..{head_sha[:12]}")
    add("```")
    add("")
    add(
        "Use that SHA, never a branch name: the local `main` ref in this "
        "worktree may be stale, and `git diff main...HEAD` has been observed "
        "to report a 35-file change where the real one is 8 files."
    )
    if ctx["diff_file"]:
        add("")
        add(f"The same diff is saved as `{ctx['out'] / ctx['diff_file']}`.")
    add("")

    add("## Files in this package")
    add("")
    if ctx["package_files"]:
        add(
            "Read every file listed here — they are the package, and nothing "
            "in them is repeated below. The paths are absolute because the "
            "only thing you were handed is this prompt's own path:"
        )
        add("")
        for path, what in ctx["package_files"]:
            add(f"- `{path}` — {what}")
    else:
        add(
            "This prompt is the whole package: no plan file was found and no "
            "input was copied. Everything else is in the repo above."
        )
    add("")

    add("## What was asked")
    add("")
    task = ctx["task"].strip()
    if task:
        add("```")
        add(task)
        add("```")
    elif ctx["plan_copied"]:
        add(
            "No task statement was recorded for this change — it was written "
            "directly rather than from a written request, so there is nothing "
            "verbatim to quote here. The plan file below is the only "
            "statement of intent this package has; read it as the request, "
            "and treat a gap between it and the diff as a finding rather "
            "than as a missing file."
        )
    else:
        add(
            "Nothing states the request: this change was written directly, "
            "and neither a task statement nor a plan was recorded. The diff "
            "is the only artefact — review it on correctness, and say which "
            "of your findings you would have decided differently had the "
            "intent been stated, rather than reporting the missing intent."
        )
    add("")
    if ctx["answers"]:
        add(
            f"The task above was amended in flight. `{ctx['out'] / 'answers.md'}` "
            "holds the decisions the user took on this change's open questions, "
            "verbatim; they bind the diff exactly as the task does. Where an "
            "answer settles something the task left open or states differently, "
            "grade against the answer. The questions themselves, and the option "
            "the run recommended, are deliberately not in this package — only "
            "what the user chose."
        )
        add("")
        add(
            "`plan.md` restates those answers as settled fact rather than "
            "quoting them, so wording that differs from an answer is not a "
            "finding. A substantive divergence is, and there the answer "
            "outranks the plan: report it under `## Plan defects`, not as a "
            "defect in the code. A `scope:` line is one of these decisions — "
            "it names a workstream the user cut, so what it covers is absent "
            "by instruction, not by oversight."
        )
        add("")
    if ctx["inputs"]:
        add(
            "The task above refers to files by a `$RUN/…` path you cannot "
            "expand. They are inputs to the work — not the run's own reports — "
            "so they are copied into this package, and where the task states "
            "the acceptance criteria in one of them, that file *is* the "
            "specification for this review:"
        )
        add("")
        for name in ctx["inputs"]:
            add(f"- `{ctx['out'] / name}`")
        add("")

    add("## The plan the change was built from")
    add("")
    if ctx["plan_copied"]:
        add(f"Read it in full: `{ctx['out'] / 'plan.md'}`")
        add("")
        if ctx["plan_structured"]:
            add(
                "It carries, in every `## WS-` block: a "
                "**verbatim spec excerpt** (`### Spec excerpt`), the observable "
                "acceptance criteria, the promised test plan, and a "
                "`### Reuse and scope` section with its `reuse:` and "
                "`keep because:` lines — plus a `do not reuse:` line wherever the "
                "planner drew that distinction, which is not every stream. It "
                "also has "
                "`## Decisions taken`, `## Project forbiddens` and `## Anti-scope` "
                "— things the change was explicitly forbidden to do."
            )
        else:
            absent = ", ".join(f"`{name}`" for name in ctx["plan_missing"])
            add(
                "It is not a full generated plan. These sections are absent, "
                "empty, or missing from at least one workstream, so do not go "
                f"looking for them: {absent}. Whatever else it "
                "contains, read as the author's own account of what the change "
                "is for and why it looks the way it does. A boundary this "
                "package never declared is a property of the package, not a "
                "defect in the change, so judge scope against what this "
                "document does say rather than reporting the absence."
            )
        add("")
        add(
            "**The plan is evidence of intent, not proof of correctness.** If "
            "the plan itself is wrong, say so rather than grading the code "
            "against a bad plan."
        )
    elif task:
        add("No plan file was found for this change; review against the task above.")
    else:
        add("No plan file was found for this change, and no task either.")
    add("")

    add("## Commits in scope")
    add("")
    counts = ctx["commit_counts"]
    if ctx["commits"]:
        untraceable = counts["total"] - counts["touching"]
        if untraceable:
            add(
                f"{counts['total']} commits are reachable in "
                f"`{base[:12]}..{head_sha[:12]}`, but {untraceable} of them "
                "leave no trace in the diff above — reverted later, or merged "
                "in from history the base already carries. Only the "
                f"{counts['touching']} that touch a file in the table are "
                "listed."
            )
            add("")
        if counts["touching"] > counts["shown"]:
            add(
                f"The {counts['shown']} most recent are listed; "
                f"{counts['touching'] - counts['shown']} earlier ones are not, "
                "because they are superseded states rather than the shipped "
                "one. Read the diff, not this list."
            )
            add("")
        add(
            "This list is context for *why* the change looks the way it does. "
            "It is not a review order:"
        )
        add("")
        for sha, subject in ctx["commits"]:
            add(f"- `{sha}` {subject}")
    else:
        add("- (none — the change is uncommitted, see below)")
    add("")

    add("## Files changed")
    add("")
    rows = ctx["numstat"]
    if rows:
        add(f"Paths are relative to `{repo}` — e.g. `{repo}/{rows[0][2]}`.")
        add("")
        add("| + | - | file |")
        add("|---:|---:|---|")
        for added, removed, path in rows[:200]:
            add(f"| {added} | {removed} | `{path}` |")
        if len(rows) > 200:
            add(f"| | | …and {len(rows) - 200} more |")
    else:
        add("(no committed file changes in base..head)")
    add("")

    if ctx["worktree"]:
        add("## Uncommitted / untracked — part of the deliverable")
        add("")
        add(
            "This workflow writes some files into the repo but never commits "
            "them (an ADR, `docs/deferred-work.md`). They are part of the "
            "work and are invisible to `git diff base..HEAD`:"
        )
        add("")
        for entry in ctx["worktree"][:100]:
            add(f"- `{entry}`")
        add("")

    add("## What to check")
    add("")
    if ctx["plan_structured"]:
        add(
            "1. **Spec / plan conformance.** Compare the diff against the "
            "verbatim spec excerpt for each workstream. Does the code do what "
            "the excerpt says, including the parts the plan calls out as "
            "binding decisions?"
        )
        add(
            "2. **Scope.** Anything changed outside the files the workstream "
            "declared? Any new *public* symbol the spec never names? Any "
            "drive-by refactor? Anything the `## Anti-scope` or "
            "`## Project forbiddens` sections rule out? A `do not reuse:` "
            "line that was reused anyway?"
        )
    else:
        add(
            "1. **Intent conformance.** Compare the diff against the intent "
            "this package states — the plan document above, or the task if "
            "that is all there is. Does the code do what it says, including "
            "anything it states as a settled decision?"
        )
        add(
            "2. **Scope.** Anything changed that the stated intent does not "
            "reach? Any new *public* symbol nothing in this package names? "
            "Any drive-by refactor? Name the change you consider out of "
            "scope and say which line of the intent excludes it — with no "
            "declared anti-scope, that reasoning is the finding, and the "
            "absent declaration is not one."
        )
    add(
        "3. **Correctness.** Real defects: wrong logic, unhandled states, "
        "races, error paths that swallow failures, type or null holes, "
        "security-relevant handling of input. Give a concrete failing "
        "scenario — inputs or state, then the wrong result."
    )
    add(
        "4. **Do the new tests measure anything?** For each new or changed "
        "assertion, name the production line whose mutation would make it "
        "fail. If you cannot name one, the assertion is vacuous — report it. "
        "Look specifically for: assertions over an empty collection, "
        "selectors that never match, `expect` calls on a value that was "
        "already true before the change, and tests that encode the same "
        "mistake the code makes. This axis matters most: in a previous run of "
        "this workflow, both rework rounds were caused by assertions that "
        "measured nothing, and none by broken production code."
    )
    add("")

    add("## How to answer")
    add("")
    add(
        "Five parts, in this order, the table first with nothing before it. "
        "Each part is triaged differently on the way back, which is why they "
        "are separate: a line-anchored defect gets verified against the diff, "
        "a plan defect gets escalated to the person who approved the plan, and "
        "a merge blocker is acted on before either. Prose folded into the "
        "table loses that routing."
    )
    add("")
    add("**1. Findings table** — most severe first:")
    add("")
    add("| severity | file:line | claim | how to falsify | tags |")
    add("|---|---|---|---|---|")
    add(
        "| HIGH | `path/to/file.ts:42` | what is wrong, in one sentence "
        "| the command, input or edit that proves it | |"
    )
    add("")
    add(
        "Severity: HIGH = ships a defect or violates the spec; MEDIUM = wrong "
        "but contained, or a test that proves nothing; LOW = style, naming, "
        "clarity."
    )
    add("")
    add(
        "`tags` carries your own reading of the row, and it is worth filling "
        "in: whoever triages this has to reach a verdict on every row, and a "
        "row that arrives untagged is one they have to re-derive from scratch. "
        "Use `PRE-EXISTING?` when you believe the fault predates the change "
        "(say which file at the base SHA you checked), `SUBSYSTEM-REWRITTEN` "
        "when it predates the change but this change rebuilds the thing that "
        "owns it, `OUT-OF-SCOPE?` when it is real but not this change's "
        "business, and `ASSUMED` when the claim rests on something you could "
        "not check. **Tag rather than drop** — a tagged row is triaged with "
        "your reasoning attached; an omitted one is simply lost."
    )
    add("")
    add(
        "**2. `## Blocking`** — anything that stops this merging regardless of "
        "the code: conflicts with the base, a branch that does not contain its "
        "own base, no CI run on the head, a missing migration. One line each, "
        "with the command you ran and its result. These are not table rows: "
        "they have no `file:line` and they outrank everything that does."
    )
    add("")
    add(
        "**3. `## Per axis`** — one line for each of the four checks above: "
        "verdict, then the specific thing that carried it. \"Clean\" is a "
        "useful answer, but say what you read to conclude it — an axis nobody "
        "can tell you looked at is an axis nobody can rely on."
    )
    add("")
    add(
        "**4. `## Plan defects`** — where the **plan** is wrong, not the code. "
        "Say what the plan asks for, why it is wrong, and what it should have "
        "asked for. Do not fold these into the table: a plan defect that "
        "arrives as a code finding gets checked against the plan and dismissed "
        "as intended behaviour, which is exactly the wrong outcome. If the "
        "plan is sound, one line saying so is worth writing."
    )
    add("")
    add(
        "**5. `## Verified for this review`** — the commands you ran and the "
        "files you read in full, then what you did **not** check. This part is "
        "load-bearing: a finding whose provenance is here can be confirmed "
        "quickly, while one that cannot be traced to a command or a file read "
        "has to be treated as a guess no matter how plausible it reads. "
        "Reviewing this kind of change without running anything is a valid "
        "choice; leaving that invisible is not."
    )
    add("")
    add("Do not fix anything — report only.")
    add("")
    return "\n".join(lines)


def main(argv: list[str]) -> int:
    ap = argparse.ArgumentParser(add_help=True, description=__doc__)
    ap.add_argument("target", nargs="?", default=None)
    ap.add_argument("--base")
    ap.add_argument("--head", default="HEAD")
    ap.add_argument("--out")
    ap.add_argument("--plan")
    ap.add_argument(
        "--task", help="file whose contents are the request, if no run task.md"
    )
    ap.add_argument("--with-diff", action="store_true")
    ap.add_argument("--quiet", action="store_true")
    ap.add_argument("--list", action="store_true", help="list recent runs and exit")
    args = ap.parse_args(argv)

    if args.list:
        print(format_recent(20))
        return 0

    run_dir, repo = resolve_target(args.target)

    plan_src = None
    if args.plan:
        plan_src = Path(args.plan).expanduser().resolve()
        if not plan_src.is_file():
            raise Fail(f"--plan file not found: {plan_src}")
    elif run_dir is not None:
        plan_src = run_dir / "plan.md"

    task = ""
    if args.task:
        task_src = Path(args.task).expanduser().resolve()
        if not task_src.is_file():
            raise Fail(f"--task file not found: {task_src}")
        task = task_src.read_text(errors="replace")
    elif run_dir is not None and (run_dir / "task.md").is_file():
        task = (run_dir / "task.md").read_text(errors="replace")

    head_sha = git(repo, "rev-parse", "--verify", f"{args.head}^{{commit}}")
    branch = git(repo, "rev-parse", "--abbrev-ref", "HEAD", check=False) or "(detached)"
    recorded = recorded_commits(run_dir, repo)
    base, warnings = resolve_base(repo, head_sha, recorded, args.base)

    rows = numstat(repo, base, head_sha)
    commits, commit_counts = commits_in_scope(
        repo, base, head_sha, [path for _, _, path in rows]
    )

    out = Path(args.out).expanduser() if args.out else None
    if out is None:
        if run_dir is None:
            raise Fail("no run directory found; pass --out DIR")
        out = run_dir / "review-package"
    out.mkdir(parents=True, exist_ok=True)
    out = out.resolve()

    diff_file = None
    if args.with_diff:
        diff_file = "diff.patch"
        (out / diff_file).write_text(git(repo, "diff", f"{base}..{head_sha}"))

    plan_copied = False
    plan_missing: list[str] = list(PLAN_SECTIONS)
    if plan_src and plan_src.is_file():
        shutil.copyfile(plan_src, out / "plan.md")
        plan_copied = True
        plan_missing = missing_plan_sections(
            (out / "plan.md").read_text(errors="replace")
        )
    plan_structured = plan_copied and not plan_missing

    inputs = []
    for src in referenced_inputs(run_dir, task):
        shutil.copyfile(src, out / src.name)
        inputs.append(src.name)

    answers = user_answers(run_dir)
    if answers:
        (out / "answers.md").write_text(answers, encoding="utf-8")

    package_files: list[tuple[Path, str]] = []
    if plan_copied:
        package_files.append(
            (
                out / "plan.md",
                "the document this change was built from, copied whole — "
                "the statement of intent you grade the diff against",
            )
        )
    if answers:
        package_files.append(
            (
                out / "answers.md",
                "the decisions the user took on this run's open questions, "
                "verbatim — amendments to the task, binding on the diff",
            )
        )
    for name in inputs:
        package_files.append(
            (
                out / name,
                "an input the task points at by a `$RUN/…` path you cannot "
                "expand; where it states the acceptance criteria it *is* the "
                "specification for this review",
            )
        )
    if diff_file:
        package_files.append(
            (
                out / diff_file,
                f"the whole `{base[:12]}..{head_sha[:12]}` diff, saved for "
                "the case where you cannot run git against the repo yourself",
            )
        )

    prompt = build_prompt(
        {
            "repo": repo,
            "branch": branch,
            "base": base,
            "head_sha": head_sha,
            "task": task,
            "answers": bool(answers),
            "plan_copied": plan_copied,
            "plan_structured": plan_structured,
            "plan_missing": plan_missing,
            "inputs": inputs,
            "package_files": package_files,
            "out": out,
            "commits": commits,
            "commit_counts": commit_counts,
            "numstat": rows,
            "worktree": working_tree_changes(repo),
            "diff_file": diff_file,
        }
    )
    prompt_path = (out / "PROMPT.md").resolve()
    prompt_path.write_text(prompt)

    if args.quiet:
        print(out)
        return 0

    print(f"run dir : {run_dir or '(none — no plan matched this repo)'}")
    print(f"repo    : {repo}")
    print(f"base    : {base}")
    print(f"head    : {head_sha}  ({branch})")
    listed = ""
    if commit_counts["shown"] != commit_counts["total"]:
        listed = f"  ({commit_counts['shown']} listed in the prompt)"
    print(f"commits : {commit_counts['total']}{listed}")
    print(f"files   : {len(rows)}")
    if inputs:
        print(f"inputs  : {', '.join(inputs)}")
    print()
    for w in warnings:
        print(f"WARNING: {w}")
    if warnings:
        print()
    print(f"package : {out}")
    for name in sorted(p.name for p in out.iterdir()):
        print(f"          {name}  ({(out / name).stat().st_size} bytes)")
    print()
    print(f"Follow instructions to review PR @{prompt_path}")
    return 0


if __name__ == "__main__":
    try:
        sys.exit(main(sys.argv[1:]))
    except Fail as exc:
        print(f"error: {exc}", file=sys.stderr)
        sys.exit(1)
